language: node_js

sudo: false

node_js:
  - '8'
  - '7'
  - '6'

script:
  - yarn run ci

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

# after_success:
#   - yarn run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
